<?php

namespace exocet\bootstrap5md;

class BootstrapPluginAsset extends \yii\web\AssetBundle
{
    /**
     * @inheritDoc
     */
    public $sourcePath = null;

    /**
     * @inheritDoc
     */
    public $css = [];

    /**
     * @inheritDoc
     */
    public $js = [];

    /**
     * @inheritDoc
     */
    public function registerAssetFiles($view)
    {
        parent::registerAssetFiles($view);

        // this mock is to make the code generated by yii\bootstrap5 work properly with my dependencies
        $jsCode = "window.bootstrap={Alert:function(n,o){},Button:function(n,o){},Carousel:function(n,o){},Collapse:function(n,o){},Dropdown:function(n,o){},Modal:function(n,o){},Offcanvas:function(n,o){},Popover:function(n,o){},Scrollspy:function(n,o){},Tab:function(n,o){},Toast:function(n,o){},Tooltip:function(n,o){}};";
        $view->registerJs($jsCode, View::POS_BEGIN);
    }
}
